config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    authenticated :user do
    root 'articles#index', as: :authenticated_root
  end
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :articles
  resources :user_surveys
  post 'articles/update_pref', to: 'articles#update_pref'
  root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  def find_for_user
    user = current_user
    article_ids = [user.last_article, user.second_last_article, user.third_last_article]

    matches = [[], [], []]

    best_matches = []
    matches.each do |match|
      match = match.map.with_index { |value, i| [value.abs, i] }
      closest = match.sort_by { |distance, _| distance}.first(5)
      indices = closest.map { |_, i| i}
      best_matches += indices
    end
    Article.where(best_matches.uniq)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_survey.rb
class UserSurvey < ApplicationRecord
  # app/models/user_survey.rb
  validates :financial_goals, :current_knowledge, :areas_of_interest, :learning_format, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    # @articles = Article.all
    # if user_signed_in?
    #   @articles = Article.find_for_user.paginate(page: params[:page], per_page: 10)
    # else
      @articles = Article.order("RANDOM()").limit(15).paginate(page: params[:page], per_page: 10)
    # end
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :url)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    user_surveys_path
  end
end

app/controllers/user_surveys_controller.rb
class UserSurveysController < ApplicationController
   def index
    @user_survey = UserSurvey.new
  end

  def new
    @user_survey = UserSurvey.new
  end

  def create
    @user_survey = UserSurvey.new(user_survey_params)
    if @user_survey.save
      redirect_to root_path, notice: 'Preferences saved!'
    else
      render :new
    end
  end

  private

  def user_survey_params
    params.require(:user_survey).permit(:financial_goals, :current_knowledge, :areas_of_interest, :learning_format)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_surveys_helper.rb
module UserSurveysHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="py-8">
  <% link_preview_data = LinkThumbnailer.generate(article.url) %>
  <% if link_preview_data %>
    <div class="card lg:card-side bg-base-100 shadow-xl bg-slate-50">
      <% if link_preview_data.images.first.src.to_s %>
      <figure class="w-2/5"><%= image_tag link_preview_data.images.first.src.to_s %></figure>
      <% end %>
      <div class="card-body w-3/5">
        <h2 class="card-title text-black">
           <%= article.title %>
        </h2>
        <p class="text-slate-900"><%= link_preview_data.description %></p>

        <!-- You can open the modal using ID.showModal() method -->


        <div class="card-actions justify-end">
        <button class="btn" onclick="my_modal_<%= article.id %>.showModal()">AI Summary</button>
        <dialog id="my_modal_<%= article.id %>" class="modal">
          <div class="modal-box w-11/12 max-w-5xl">
            <h3 class="font-bold text-lg"><%= article.title %></h3>
            <p class="py-4"><%= article.summary %></p>
            <div class="modal-action">
              <form method="dialog">
                <!-- if there is a button, it will close the modal -->
                <button class="btn">Close</button>
              </form>
            </div>
          </div>
        </dialog>
        </div>

        <div class="card-actions justify-end">
          <button class="btn btn-primary">
            <%= link_to "Read More", article.url %>
          </button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mx-auto px-8">
  <div>
    <h1 class="text-slate-200 text-3xl">
    <% if current_user %>
      Hello, <%= current_user.email %> !
    <% else %>
      Hello!
    <% end %>
    </h1>
  <h2 class="text-slate-200 text-lg">Your learning for today:</h2>
  </div>

  <div id="articles">
    <% @articles.each do |article| %>
        <%= render article %>
    <% end %>
  </div>
  <div class="join">
    <%= will_paginate @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<div class="flashes mt-2">
  <% flash.each do |key, value| %>
    <% if key == 'alert' or key == 'notice' %>
      <%= content_tag(:div, value, class: "flash #{key}", id: "#{key}") %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<div class="static shadow bg-indigo-400 navbar bg-base-100 px-24">
  <div class="flex-1">
    <%= link_to root_path do %>
               <div class="flex items-center">
               <div class="mr-2">
                  <%= image_tag 'logo.png', alt: 'SkillUp Logo', height: '', width: '100', class: '' %>
               </div>
               <div>
                  <h1 class="text-slate-800 text-2xl font-mono">
                  SkillUp
                  </h1>
               </div>
               </div>
            <% end %>
  </div>


    <% if user_signed_in? %>
      <%= link_to 'Log Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "pr-7 text-black" %>

      <%= link_to edit_user_registration_path do %>
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="black" class="w-10 h-10">
              <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
            </svg>
          </div>
        </label>
      <% end %>
    <% else %>
      <%= link_to 'Sign Up', new_user_registration_path, class: "pr-7 text-black" %>
      <%= link_to 'Sign In', new_user_session_path, class: "pr-7 text-black" %>
    <% end %>




  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkillupWebapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.4.2/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <%= render "/layouts/header" %>
    <main class="container mx-auto mt-10 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/user_surveys/index.html.erb
<div class="min-h-screen flex justify-center">
   <div class="max-w-md w-full p-6 text-slate-200 shadow-md">
<h1 class="text-4xl py-4">
  Welcome to skill Up!
</h1>
<h2 class="text-lg py-4">We would like to learn more about you, so we can recommend you the best content that will meet your learning goal:</h2>

<%= form_with(model: @user_survey, url: user_surveys_path, method: :post) do |form| %>
  <div>
    <label for="financial_goals">
      <h3>Financial Goals:</h3>
      </label>
    <%= form.select :financial_goals, ['Saving for a home', 'Investing for retirement', 'Debt repayment', 'Microfinance', 'Business investment'] %>
  </div>

  <div>
    <label for="current_knowledge">
      <h3>Current Knowledge Level:</h3>
    </label>
    <%= form.select :current_knowledge, ['Beginner', 'Intermediate', 'Advanced'] %>
    <%# <%= form.text_area :current_knowledge, rows: 3 %> 
  </div>

  <div>
    <label for="areas_of_interest">
      <h3>Areas of Interest:</h3>
    </label>
    <%# <%= form.text_area :areas_of_interest, rows: 3 %> 
    <%= form.select :areas_of_interest, ['Budgeting', 'Investing', 'Taxes', 'Personal finance tips'] %>
  </div>

  <div>
    <label for="learning_format">
      <h3>Preferred Learning Format:</h3>
    </label>
    <%# <%= form.text_area :learning_format, rows: 3 %> 
    <%= form.select :learning_format, ['Short articles', 'Videos', 'Interactive quizzes', 'Podcasts'] %>
  </div>

  <div>
    <button class="btn btn-primary">
    <%= form.submit 'Submit Survey' %>
    </button>
  </div>
<% end %>
</div>
</div>